#!/usr/bin/env python3
"""Generate manuscript figures from patient_level_data.csv.

Produces:
  - figure1_barrier_prevalence_vs_cost.png  (main text Figure 1)

eFigures 1-4 are generated by the upstream pipeline
(run_friction_analysis.py) from encounter-level data and are not
reproducible from the patient-level extract alone.
"""

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


MINUTES_PER_NOTE = {
    "Scheduling": 8.1,
    "Transportation": 37.5,
    "Paperwork": 23.0,
    "Authorization": 20.0,
}

BARRIER_COLS = {
    "Scheduling": ("has_scheduling_barrier", "count_scheduling_flag"),
    "Transportation": ("has_transportation_barrier", "count_transportation_flag"),
    "Paperwork": ("has_paperwork_barrier", "count_documentation_flag"),
    "Authorization": ("has_authorization_barrier", "count_authorization_flag"),
}

RBRVS_WAGE = 33.40


def load_data(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    df["has_any_barrier"] = (df["barrier_count"] > 0).astype(int)
    return df


def compute_figure1_data(df: pd.DataFrame) -> pd.DataFrame:
    """Compute prevalence and mean RBRVS cost per affected patient by barrier type."""
    rows = []
    for bname, (has_col, count_col) in BARRIER_COLS.items():
        sub = df[df[has_col] == 1]
        prevalence_pct = len(sub) / len(df) * 100
        mins = MINUTES_PER_NOTE[bname]
        cost = sub[count_col] * mins / 60.0 * RBRVS_WAGE
        rows.append({
            "barrier": bname,
            "prevalence_pct": prevalence_pct,
            "mean_cost_rbrvs": cost.mean(),
            "n_affected": len(sub),
        })
    return pd.DataFrame(rows)


def plot_figure1(fig_df: pd.DataFrame, output_path: Path) -> None:
    """Scatter plot: barrier prevalence (x) vs mean per-patient cost (y).

    Circle size proportional to number of affected patients.
    """
    fig, ax = plt.subplots(figsize=(6, 5))

    # Scale circle sizes so the range is visually distinguishable
    size_scale = fig_df["n_affected"] / fig_df["n_affected"].max() * 800 + 200

    ax.scatter(
        fig_df["prevalence_pct"],
        fig_df["mean_cost_rbrvs"],
        s=size_scale,
        c="#2c7bb6",
        alpha=0.7,
        edgecolors="black",
        linewidths=0.8,
        zorder=3,
    )

    # Label each point
    for _, row in fig_df.iterrows():
        ax.annotate(
            row["barrier"],
            (row["prevalence_pct"], row["mean_cost_rbrvs"]),
            textcoords="offset points",
            xytext=(0, 14),
            ha="center",
            fontsize=10,
            fontweight="bold",
        )

    ax.set_xlabel("Patient-Level Prevalence (%)", fontsize=11)
    ax.set_ylabel(
        "Mean Cost per Affected Patient, $ (RBRVS $33.40/hr)", fontsize=11
    )
    ax.set_xlim(0, max(fig_df["prevalence_pct"]) * 1.25)
    ax.set_ylim(0, max(fig_df["mean_cost_rbrvs"]) * 1.25)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(axis="y", alpha=0.3)

    # Size legend
    legend_sizes = [2000, 6000, 12000]
    legend_labels = ["2,000", "6,000", "12,000"]
    for ls, ll in zip(legend_sizes, legend_labels):
        ax.scatter(
            [], [],
            s=ls / fig_df["n_affected"].max() * 800 + 200,
            c="white",
            edgecolors="black",
            linewidths=0.8,
            label=f"n = {ll}",
        )
    ax.legend(
        title="Affected patients",
        loc="upper right",
        framealpha=0.9,
        fontsize=9,
        title_fontsize=9,
    )

    fig.tight_layout()
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate manuscript figures from patient_level_data.csv"
    )
    parser.add_argument(
        "--patient-data",
        type=Path,
        default=Path(__file__).parent / "data" / "patient_level_data.csv",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).parent / "output",
    )
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    df = load_data(args.patient_data)
    print(f"Loaded {len(df):,} patients")

    fig_df = compute_figure1_data(df)
    print("\nFigure 1 data:")
    for _, row in fig_df.iterrows():
        print(
            f"  {row['barrier']}: prevalence={row['prevalence_pct']:.1f}%, "
            f"cost=${row['mean_cost_rbrvs']:.2f}, n={row['n_affected']:,}"
        )

    plot_figure1(fig_df, args.output_dir / "figure1_barrier_prevalence_vs_cost.png")


if __name__ == "__main__":
    main()
