#!/usr/bin/env python3
"""Revision 1 — regenerate eFigure 1 (ROC) and eFigure 2 (temporal) with burden terminology.

eFigure 3 (Kaplan-Meier) is regenerated by regenerate_km.py (uses lifelines).

ROC curves are drawn from the archived classifiers; curves are labeled by burden
type only (AUROC values are reported in eTable 2), so the figure carries no AUC
annotation that could drift from the table under a different scikit-learn version.

Requires: archived models (outputs/models/*.joblib), annotation_sample_adjudicated.csv,
friction_events.parquet. Run with a Python that has pyarrow + scikit-learn.
"""
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
import joblib
from sklearn.metrics import roc_curve

NB = Path.home() / "waymark-local/notebooks/admin_friction"
OUT = NB / "revision1" / "figures"
MODELS = NB / "outputs" / "models"
THRESH_CATS = ["scheduling", "transportation", "documentation", "authorization"]
LABEL = {"scheduling": "Scheduling", "transportation": "Transportation",
         "documentation": "Paperwork", "authorization": "Prior authorization"}
PY_TOTAL = 147846.0


def efigure1_roc():
    annot = pd.read_csv(NB / "outputs" / "annotation_sample_adjudicated.csv")
    dates = pd.to_datetime(annot["dateOfEncounter"])
    q1, q2 = dates.quantile([0.6, 0.8])
    test = dates > q2
    vec = joblib.load(MODELS / "tfidf.joblib")
    Xt = vec.transform(annot.loc[test, "text"].fillna(""))
    fig, ax = plt.subplots(figsize=(5, 5))
    styles = ["-", "--", "-.", ":"]
    for cat, ls in zip(THRESH_CATS, styles):
        clf = joblib.load(MODELS / f"{cat}_clf.joblib")
        proba = clf.predict_proba(Xt)[:, 1]
        ytrue = annot.loc[test, f"{cat}_gold"].astype(int).values
        fpr, tpr, _ = roc_curve(ytrue, proba)
        ax.plot(fpr, tpr, ls, color="black", lw=1.4, label=LABEL[cat])
    ax.plot([0, 1], [0, 1], color="gray", lw=0.8, ls=(0, (3, 3)), label="Chance")
    ax.set_xlabel("False-positive rate")
    ax.set_ylabel("True-positive rate")
    ax.set_xlim(0, 1); ax.set_ylim(0, 1.02)
    ax.legend(loc="lower right", fontsize=8, frameon=True)
    ax.spines["top"].set_visible(False); ax.spines["right"].set_visible(False)
    fig.tight_layout()
    OUT.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT / "eFigure1_roc_curves.png", dpi=300, bbox_inches="tight")
    plt.close(fig)
    print("wrote eFigure1_roc_curves.png")


def efigure2_temporal():
    fe = pd.read_parquet(NB / "outputs" / "friction_events.parquet")
    fe["month"] = pd.to_datetime(fe["note_dt"], errors="coerce").dt.to_period("M")
    fe = fe.dropna(subset=["month"])
    months = sorted(fe["month"].unique())
    py_per_month = PY_TOTAL / len(months)
    fig, ax = plt.subplots(figsize=(7, 4))
    styles = ["-", "--", "-.", ":"]
    for cat, ls in zip(THRESH_CATS, styles):
        rate = (fe.groupby("month")[f"{cat}_flag"].sum().reindex(months).fillna(0)
                / py_per_month * 100)
        ax.plot(range(len(months)), rate.values, ls, color="black", lw=1.3, label=LABEL[cat])
    ax.set_xlabel("Study month")
    ax.set_ylabel("Documented burden incidence\n(flagged notes per 100 patient-years)")
    ax.legend(fontsize=8, frameon=True, ncol=2)
    ax.spines["top"].set_visible(False); ax.spines["right"].set_visible(False)
    fig.tight_layout()
    fig.savefig(OUT / "eFigure2_temporal_trends.png", dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote eFigure2_temporal_trends.png ({len(months)} months)")


if __name__ == "__main__":
    efigure1_roc()
    efigure2_temporal()
    print("done")
